Upgrade openai 1.0
livingbio/gpt-fn pull request #185
Opened 2023-12-19 08:26 UTC by jeff3071

# Context

Fix #133 

# Summary

新增get_client()，增加抓取環境變數判斷api_type
vcr cassettes update

# Testing Instructions

```
pytest ./src
```

2023-12-19 09:25 UTC, lucemia requested changes
看能不能不要對 Client 使用 Any

2023-12-19 09:25 UTC, lucemia commented on src/gpt_fn/completion.py
> +def get_client(model: str, api_settings: APISettings = APISettings(), Async: bool = False) -> OpenAI | AzureOpenAI | AsyncOpenAI | AsyncAzureOpenAI:
```suggestion
def get_client(model: str, api_settings: APISettings = APISettings(), Async: bool = False) -> OpenAI | AsyncOpenAI:
```

AzureOpenAI 繼承 OpenAI
AsyncAzureOpenAI 繼承 AsyncOpenAI

2023-12-19 09:25 UTC, lucemia commented on src/gpt_fn/completion.py
> +    client: Any = get_client(model, api_settings, Async=False)
```suggestion
    client: OpenAI = get_client(model, api_settings, Async=False)
```

2023-12-20 01:52 UTC, jeff3071 commented
- 更改get_client return type: OpenAI、AsyncOpenAI
- client不使用Any，呼叫create時mypy會報錯 (kwargs type dict[str, Object])，把kwargs標為dict[str, Any]解決

2023-12-20 04:34 UTC, lucemia approved these changes
Thanks @jeff3071

2023-12-20 04:38 UTC, merged